--OpenOS Startup File
print("Loading APIs...")
os.loadAPI("/lib/libde")
os.loadAPI("/lib/libtext")
os.loadAPI("/lib/libget")
print("Checking for updates...")
shell.run("ac-get", "update")
print("Running Splash...")

term.setBackgroundColor(colors.white)
term.clear()
splashimage = paintutils.loadImage("/cfg/wallpaper.bg")
paintutils.drawImage(splashimage,1,1)
libtext.cPrint("OpenOS",12)
sleep(0.5)
shell.run("/bin/desktop")